#!/usr/bin/env node

var fs = require('fs');
// var file = process.argv[2];
var level = require('./level1.json');
var readline = require('readline');

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});


var currentRoom = {};
var doorsArray = [];
var doorDirections = [];
var newRoom;
var treasureRoom = {};

// Find where they went
var whichRoom = function (roomName) {
	level.rooms.forEach(function(obj) {
		if (obj.name === roomName) {
			currentRoom = obj;
		}
	});
};

// Count the number of doors in the current room
var countTheDoors = function (obj) {
  doorsArray = [];
	var d1 = ""; var d2 = "";var d3 = ""; var d4 = "";
	if (obj.north) {
		doorsArray.push(obj.north);
		doorDirections.push('north');
		d1 = ', one to the north';
	}
	if (obj.south) {
		doorsArray.push(obj.south);
		doorDirections.push('south');
		d2 = ', one to the south';
	}
	if (obj.east) {
		doorsArray.push(obj.east);
		doorDirections.push('east');
		d3 = ', one to the east';
	}
	if (obj.west) {
		doorsArray.push(obj.west);
		doorDirections.push('west');
		d4 = ', one to the west';
	}
	console.log('You are standing in ' + currentRoom.name + '. You notice there are ' + doorsArray.length +
		' doors in this weird little room' +
		d1 + d2 + d3 + d4 + '.');
};

var describeDirection = function (obj) {
	countTheDoors(obj);

};

// console.log(currentRoom);
// console.log('You\'re currently in ' + currentRoom.name);

// console.log(doorsArray);

var runGame = function (roomObj) {
	countTheDoors(roomObj);
	rl.question("Which direction do you want to proceed? ", function(direction) {
		console.log("You have traveled", direction);
			newRoom = roomObj[direction];
			console.log('You are now in room ' + newRoom);
			whichRoom(newRoom);
      runGame(currentRoom);
	});
};

// Find the starting room
level.rooms.forEach(function(obj) {
  if (obj.entrance) {
    currentRoom = obj;
  }
});

// Find the treasure room
level.rooms.forEach(function(obj) {
  if (obj.treasure) {
    treasureRoom = obj;
  }
});

// Run the game

runGame (currentRoom);

// console.log('You have found the treasure');
// rl.close();






