#!/usr/bin/env node

var fs = require('fs');
// var file = process.argv[2];
var level = require('./level1.json');
var readline = require('readline');

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});


var currentRoom = {};

// var lookAround = function(inRoom) {
// 	var north = level.room.north;
//   var south = level.room.south;
//   var east = level.room.east;
//   var west = level.room.west;
//   var roomArray = [north, south, east, west];
//   return roomArray;
// };

// Find the starting room
level.rooms.forEach(function(obj) {
  if (obj.entrance) {
    currentRoom = obj;
  }
});

console.log(currentRoom);
console.log('You\'re currently in ' + currentRoom.name);
// console.log('You find yourself in a room. It has ' +
// 	lookAround(currentRoom).length + " doors");
// console.log(lookAround(currentRoom));

rl.close();

// rl.question("What is your first number?", function(number1) {
// 	console.log("Your first number is", number1);
// 	rl.question("What is your second number?", function(number2) {
// 		console.log("Your second number is", number2);
// 		// TODO: Log the answer in a database
// 	  	console.log("Thank you! Your total is:", sum(number1, number2));
//   		rl.close();
// 	});
// });
