#!/usr/bin/env node

var fs = require('fs');
// var file = process.argv[2];
var level = require('./level1.json');
var readline = require('readline');

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});


var currentRoom = {};
var doorsArray = [];
var doorDirections = [];

// Find the starting room
level.rooms.forEach(function(obj) {
  if (obj.entrance) {
    currentRoom = obj;
  }
});

// Count the number of doors in the current room
var countTheDoors = function (obj) {
	var d1 = ""; var d2 = "";var d3 = ""; var d4 = "";
	if (obj.north) {
		doorsArray.push(obj.north);
		doorDirections.push('north');
		d1 = ', one to the north';
	}
	if (obj.south) {
		doorsArray.push(obj.south);
		doorDirections.push('south');
		d2 = ', one to the south';
	}
	if (obj.east) {
		doorsArray.push(obj.east);
		doorDirections.push('east');
		d3 = ', one to the east';
	}
	if (obj.west) {
		doorsArray.push(obj.west);
		doorDirections.push('west');
		d4 = ', one to the west';
	}
	console.log('You see ' + doorsArray.length + ' doors in this room' + 
		d1 + d2 + d3 + d4 + '.');
};

var describeDirection = function (obj) {
	countTheDoors(obj);

};

// console.log(currentRoom);
// console.log('You\'re currently in ' + currentRoom.name);
countTheDoors(currentRoom);
console.log('You notice that there are ' + doorsArray.length + 
	' doors in this weird little room.');
console.log(doorsArray);


rl.close();

// rl.question("What is your first number?", function(number1) {
// 	console.log("Your first number is", number1);
// 	rl.question("What is your second number?", function(number2) {
// 		console.log("Your second number is", number2);
// 		// TODO: Log the answer in a database
// 	  	console.log("Thank you! Your total is:", sum(number1, number2));
//   		rl.close();
// 	});
// });
